---
- name: docker-compose | register uname -s
  command: uname -s
  register: uname_s

- name: docker-compose | register uname -m
  command: uname -m
  register: uname_m

- name: docker-compose | download docker-compose script
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.13.0/docker-compose-{{ uname_s }}-{{ uname_m }}"
    dest: /usr/local/bin/docker-compose
    mode: 0755
  become: true
  become_method: sudo
