---
- name: python | ensure python3 is installed
  apt:
    state: present
    name: python3
  become: true
  become_method: sudo

- name: python | install python packages for projects
  apt:
    state: present
    name: "{{ item }}"
  with_items:
    - python-pip
    - python3-dev
    - python3-venv
    - python3-pyaudio
    - python3-setuptools
    - python3-tk
  become: true
  become_method: sudo

- name: python | make sure pip is up to date
  command: pip install -U pip setuptools
  become: true
  become_method: sudo
  ignore_errors: "{{ ansible_check_mode }}"

- name: python | install docker-py
  command: pip install docker-py
  become: true
  become_method: sudo
  ignore_errors: "{{ ansible_check_mode }}"
