---
- name : maven | download maven archive
  get_url:
    url : http://apache.mirror.globo.tech/maven/maven-3/3.5.0/binaries/apache-maven-3.5.0-bin.tar.gz
    dest: /tmp/apache-maven-3.5.0-bin.tar.gz

- name : maven | unpack binary archive in installation folder
  unarchive:
    src: /tmp/apache-maven-3.5.0-bin.tar.gz
    dest: /opt/apache/maven/maven-3-5-0

- name: maven | set MAVEN_HOME and update PATH in .profile
  blockinfile:
    path: "{{ ansible_env.HOME }}/.profile"
    state: present
    insertafter: EOF
    block: |
      'export MAVEN_HOME=/opt/apache/maven-3-5-0'
      'export PATH="$PATH:$MAVEN_HOME/bin"'
  become: true
  become_user: "{{ ansible_env.USER }}"
