---
- name : maven | download maven archive
    get_url:
      url : http://apache.mirror.globo.tech/maven/maven-3/3.5.0/binaries/apache-maven-3.5.0-bin.tar.gz
      dest: /tmp/apache-maven-3.5.0-bin.tar.gz

- name : maven | unpack binary archive in installation folder
    unarchive:
        src: /tmp/apache-maven-3.5.0-bin.tar.gz
        dest: /opt/apache/maven/maven-3-5-0
    creates: /opt/apache/maven/maven-3-5-0

- name: maven | set MAVEN_HOME in .profile
  blockinfile:
      path: "{{ ansible_env.HOME }}/.profile"
      state: present
      insertafter: '^export JAVA_HOME'
      line: "export MAVEN_HOME=/opt/apache/maven-3-5-0"
  become: true
  become_user: "{{ user }}"

- name: maven | update PATH in .profile
    blockinfile:
      path: "{{ ansible_env.HOME }}/.profile"
      state: present
      regexp: "^export PATH=\"\$PATH:\$JAVA_HOME/bin\"$"
      line: "export PATH=\"$PATH:$JAVA_HOME/bin:$MAVEN_HOME/bin\""
  become: true
  become_user: "{{ user }}"

#- name: maven | test maven installation
