---
- name: java | add java ppa
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version >= "16.04"
  apt_repository:
    repo: "ppa:webupd8team/java"
    state: present
    update_cache: yes
  become: true
  become_method: sudo

- name: java | accept oracle terms
  debconf:
    name: "{{ item }}"
    question: 'shared/accepted-oracle-license-v1-1'
    vtype: 'select'
    value: 'true'
  with_items:
    - oracle-java8-installer
  become: true
  become_method: sudo

- name: java | nuke java7
  apt:
    state: absent
    name: "{{ item }}"
  with_items:
    - oracle-java7-installer
    - oracle-java7-unlimited-jce-policy
  become: true
  become_method: sudo

- name: java | install java8 with default & jce-policy
  apt:
    state: present
    name: "{{ item }}"
  with_items:
    - oracle-java8-installer
    - oracle-java8-set-default
    - oracle-java8-unlimited-jce-policy
  become: true
  become_method: sudo

- name: java | set JAVA_HOME in .profile
  blockinfile:
      path: "{{ ansible_env.HOME }}/.profile"
      state: present
      insertafter: EOF
      block: |
        "export JAVA_HOME=/usr/bin/java"
        "export PATH="$PATH:$JAVA_HOME/bin"
  become: true
  become_user: "{{ ansible_env.USER }}"
