---
- name: java | add java ppa
  become: true
  become_method: sudo
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version >= "16.04"
  apt_repository:
    repo: "ppa:webupd8team/java"
    state: present
    update_cache: yes

- name: java | accept oracle terms
  become: yes
  become_method: sudo
  debconf:
    name: '{{ item }}'
    question: 'shared/accepted-oracle-license-v1-1'
    vtype: 'select'
    value: 'true'
  with_items:
    - oracle-java8-installer

- name: java | nuke java7
  become: yes
  become_method: sudo
  apt:
    state: absent
    name: {{ item }}
  with_items:
    - oracle-java7-installer
    - oracle-java7-unlimited-jce-policy

- name: java | install java8 with default & jce-policy
  become: yes
  become_method: sudo
  apt:
    state: present
    name: '{{ item }}'
  with_items:
    - oracle-java8-installer
    - oracle-java8-set-default
    - oracle-java8-unlimited-jce-policy
